name: Mac Demo Test
on: [push, pull_request]

jobs:
  test-mac:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mousearm-test
          python-version: "3.11"
          architecture: x64 
          channels: opensim-org,defaults
          conda-options: "--retries 3"

      - name: Install opensim and dependencies
        run: |
          conda install opensim "numpy<2" matplotlib pandas scipy -y

      - name: Install library with uv
        run: |
          pip install uv
          uv pip install --no-deps .

      - name: Run Demo
        run: |
          DEMO_DIR=$(find . -type d -name "Demo" | head -n 1)
          echo "Found Demo directory at: $DEMO_DIR"
          cd "$DEMO_DIR"
          python Demo.py
